import nx from '@nx/eslint-plugin';
import tseslint from 'typescript-eslint';
import unicorn from 'eslint-plugin-unicorn';
import importPlugin from 'eslint-plugin-import';
import prettierRecommended from 'eslint-plugin-prettier/recommended';

/**
 * Root ESLint config — the zero-tolerance posture for the whole workspace
 * (issue #11 / ADR-0009). Every project's `eslint.config.mjs` spreads this.
 *
 * Layers, in order:
 *  1. Nx base/TS/JS presets + module-boundary enforcement (ADR-0009).
 *  2. typescript-eslint `strict-type-checked` + `stylistic-type-checked`
 *     (type-aware; the strongest stock rule sets).
 *  3. eslint-plugin-import + eslint-plugin-unicorn hygiene.
 *  4. eslint-plugin-prettier LAST — formatting is a lint error, not a hint.
 *
 * Framework layers (React/Next, NestJS) live in the per-app configs so their
 * rules only touch the projects they apply to.
 */
export default tseslint.config(
  ...nx.configs['flat/base'],
  ...nx.configs['flat/typescript'],
  ...nx.configs['flat/javascript'],
  {
    ignores: [
      '**/dist',
      '**/out-tsc',
      '**/.next',
      '**/coverage',
      '**/node_modules',
      // Regenerated by `next build` on every run; not ours to format.
      '**/next-env.d.ts',
    ],
  },

  // --- Module boundaries: the ADR-0009 depConstraints, verbatim. ---
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.js', '**/*.jsx', '**/*.cjs', '**/*.mjs'],
    rules: {
      '@nx/enforce-module-boundaries': [
        'error',
        {
          enforceBuildableLibDependency: true,
          allow: [
            '^.*/eslint(\\.base)?\\.config\\.[cm]?[jt]s$',
            '^.*/eslint\\.react\\.mjs$',
          ],
          depConstraints: [
            { sourceTag: 'scope:shared', onlyDependOnLibsWithTags: ['scope:shared'] },
            {
              sourceTag: 'scope:api',
              onlyDependOnLibsWithTags: ['scope:api', 'scope:shared'],
            },
            {
              sourceTag: 'scope:web',
              onlyDependOnLibsWithTags: ['scope:web', 'scope:shared'],
            },
            { sourceTag: 'type:domain', onlyDependOnLibsWithTags: ['type:domain'] },
            {
              sourceTag: 'type:data-access',
              onlyDependOnLibsWithTags: ['type:domain', 'type:data-access'],
            },
            {
              sourceTag: 'type:ui',
              onlyDependOnLibsWithTags: ['type:domain', 'type:ui'],
            },
            { sourceTag: 'type:app', onlyDependOnLibsWithTags: ['*'] },
          ],
        },
      ],
    },
  },

  // --- Type-aware TypeScript: the strongest stock rule sets. ---
  {
    files: ['**/*.ts', '**/*.tsx', '**/*.cts', '**/*.mts'],
    extends: [
      tseslint.configs.strictTypeChecked,
      tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Surface unused symbols as errors, but let a leading `_` mark intent.
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },

  // --- Import hygiene. TS itself resolves modules (workspace packages,
  //     nodenext, custom conditions) more accurately than any resolver, so
  //     the resolution rules are delegated to the compiler; ordering and
  //     dedupe stay on. ---
  importPlugin.flatConfigs.recommended,
  {
    rules: {
      'import/no-unresolved': 'off',
      'import/named': 'off',
      'import/namespace': 'off',
      'import/default': 'off',
      'import/no-named-as-default-member': 'off',
      'import/order': [
        'error',
        {
          'newlines-between': 'never',
          alphabetize: { order: 'asc', caseInsensitive: true },
        },
      ],
      'import/no-duplicates': 'error',
    },
  },

  // --- Unicorn: broad correctness/idiom rules. ---
  unicorn.configs.recommended,
  {
    rules: {
      // The workspace convention is descriptive names, not enforced casing;
      // and abbreviations like `db`, `req`, `params` read fine here.
      'unicorn/filename-case': 'off',
      'unicorn/prevent-abbreviations': 'off',
      // Framework-mandated file names (`next-env.d.ts`, `tsconfig.lib.json`)
      // can't be renamed; this rule fights the tooling, not our code.
      'unicorn/name-replacements': 'off',
      // unicorn@72 ships `defaultOptions: [null]` for this rule, which ESLint 9
      // auto-applies and then rejects against the rule's own schema. Pin valid
      // explicit options so the rule (which we want) actually loads.
      'unicorn/logical-assignment-operators': [
        'error',
        'always',
        { enforceForIfStatements: true },
      ],
    },
  },

  // --- Prettier LAST: disables conflicting stylistic rules and turns any
  //     remaining formatting drift into an error. ---
  prettierRecommended,

  // --- Generated tooling & config files (build/test infra). Not product
  //     code: they live outside the TS programs and use CommonJS. Type-aware
  //     linting is disabled and the CommonJS-module rules are relaxed. This is
  //     a narrow, file-scoped, documented exception — the accepted alternative
  //     to blanket inline `eslint-disable` comments. ---
  {
    files: [
      '**/*.js',
      '**/*.cjs',
      '**/*.mjs',
      '**/*.jsx',
      '**/jest.config.{ts,cts,mts}',
      '**/jest.preset.js',
    ],
    extends: [tseslint.configs.disableTypeChecked],
    rules: {
      'unicorn/prefer-module': 'off',
      'unicorn/prefer-node-protocol': 'off',
      'unicorn/no-anonymous-default-export': 'off',
      '@typescript-eslint/no-require-imports': 'off',
    },
  },

  // --- Ambient declaration files are generated; triple-slash references are
  //     the idiom there. ---
  {
    files: ['**/*.d.ts'],
    rules: {
      '@typescript-eslint/triple-slash-reference': 'off',
    },
  },

  // --- Service workers run in the ServiceWorkerGlobalScope, where `self` is
  //     the canonical global per the spec — not a stand-in for `globalThis`. ---
  {
    files: ['**/public/sw.js'],
    rules: {
      'unicorn/prefer-global-this': 'off',
    },
  },
);
