version: '3.8'

services:
  frontend:
    build:
      context: ../frontend/rv-checklist-app
      dockerfile: ../../docker/frontend.Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - backend
    environment:
      - NODE_ENV=production

  backend:
    build:
      context: ../backend/backend
      dockerfile: ../../docker/backend.Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/rv-checklist
      - JWT_SECRET=your_jwt_secret_here
      - JWT_EXPIRATION=86400

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      - MONGO_INITDB_DATABASE=rv-checklist

volumes:
  mongodb_data:
