/*
 * The RV Checklist service worker (ADR-0028, issue #150).
 *
 * Hand-rolled on the `serwist` runtime rather than generated by
 * `@serwist/next`, which forces the whole app onto the webpack builder. This
 * file is the source; `sw/build.mjs` bundles it with esbuild after `next
 * build`, injecting the precache manifest, and writes `public/sw.js`.
 *
 * The model is **cached pages, not an app shell**. Navigations stay
 * network-first, so online request and response behaviour is exactly what it
 * was before this worker existed: every navigation still reaches the edge
 * middleware and is still answered by it. What the worker adds is a copy of
 * every page the owner has actually opened, so off grid those pages still
 * render and the hooks-only components re-read the PowerSync local store
 * (ADR-0029). A route the owner has never opened has no copy to serve, and
 * gets the branded `/offline` page instead.
 */
import {
  ATTACHMENT_OUTBOX_SYNC_TAG,
  OUTBOX_BROADCAST_CHANNEL,
} from '@rv-checklist/domain';
import {
  CacheableResponsePlugin,
  CacheFirst,
  ExpirationPlugin,
  NetworkFirst,
  Serwist,
  type PrecacheEntry,
  type RouteHandlerCallbackOptions,
  type RouteMatchCallbackOptions,
} from 'serwist';
import { respondToAttachment } from './attachment-cache.js';
import { handleSwMessage } from './message-handler.js';
import { flushOutbox } from './outbox-flush.js';
import { openOutboxDatabase } from './outbox-store.js';

declare const self: ServiceWorkerGlobalScope & {
  /** Injected by `sw/build.mjs` at build time. */
  readonly __SW_MANIFEST: (PrecacheEntry | string)[];
};

/**
 * The Background Sync API has no `lib.webworker.d.ts` types — TypeScript has
 * never shipped them (Chromium-only, no cross-browser spec to standardize
 * against). Declared locally rather than pulled in from a `@types` package
 * that would bring the rest of an unused surface with it.
 */
interface SyncEvent extends ExtendableEvent {
  readonly tag: string;
}

/** `NEXT_PUBLIC_API_BASE_URL`, injected by `sw/build.mjs` (this worker is never a Next.js runtime). */
declare const __API_BASE_URL__: string;

/** The precached, data-free page shown for a route with no cached copy. */
const OFFLINE_URL = '/offline';

const YEAR_IN_SECONDS = 60 * 60 * 24 * 365;

/**
 * A document navigation: the browser asking for a page, as opposed to the
 * App Router asking for an RSC payload for one.
 */
function isNavigation({
  request,
  sameOrigin,
}: RouteMatchCallbackOptions): boolean {
  return sameOrigin && request.mode === 'navigate';
}

/**
 * An App Router payload request. Next varies these by the router state tree,
 * the prefetch flags and `Next-Url`, and hashes all of that into the `_rsc`
 * search param — so the request URL, which is what Cache Storage keys on,
 * already distinguishes payloads that are not interchangeable. A cache hit is
 * therefore a payload that is valid for this exact navigation; on a miss,
 * `fetchServerResponse` falls back to a full browser navigation, which the
 * cached documents answer.
 */
function isRouterPayload({
  request,
  sameOrigin,
}: RouteMatchCallbackOptions): boolean {
  return sameOrigin && request.headers.get('rsc') === '1';
}

function isBuildAsset({ url, sameOrigin }: RouteMatchCallbackOptions): boolean {
  return sameOrigin && url.pathname.startsWith('/_next/static/');
}

/**
 * An attachment download (ADR-0026, ADR-0028) — the API's proxied byte
 * stream, so cross-origin against `NEXT_PUBLIC_API_BASE_URL` rather than this
 * worker's own origin (ADR-0019: the browser calls the API directly).
 * Matched on path alone; current-trip warming (issue #151) is what puts the
 * bytes in cache ahead of the first request, and {@link respondToAttachment}
 * is what serves them cache-first once they are there.
 */
function isAttachmentRequest({ url }: RouteMatchCallbackOptions): boolean {
  return url.pathname.startsWith('/attachments/');
}

const serwist = new Serwist({
  precacheEntries: self.__SW_MANIFEST,
  precacheOptions: {
    cleanupOutdatedCaches: true,
    plugins: [
      {
        // Serwist's default is to copy a followed redirect into the precache
        // and treat anything under 400 as cacheable. Every URL in the manifest
        // is a same-origin static file that answers 200 or is broken, so a
        // redirect can only mean the middleware answered instead — and storing
        // the sign-in page as, say, the SDK's worker would last until the SDK
        // version changed. Making `/sw.js`, `/offline` and `/@powersync/`
        // public prefixes is what stops that arising; this is the guard
        // against it arising some other way.
        //
        // Refusing an entry fails the install, and the install then stalls
        // rather than rejecting — `parallel` in `@serwist/utils` resolves its
        // queues from inside an async executor, so a throw never reaches the
        // enclosing promise. Either way no worker activates and the browser
        // retries on the next page load, which is the outcome we want; it is
        // just quieter than it looks.
        //
        // `null` is Serwist's "do not cache this"; `undefined` is not.
        cacheWillUpdate: ({ response }) =>
          Promise.resolve(
            response.status === 200 && !response.redirected
              ? response
              : // eslint-disable-next-line unicorn/no-null
                null,
          ),
      },
    ],
  },
  cacheId: 'rv-checklist',
  // A deploy takes effect on the next load, with no reload prompt: the new
  // worker skips the waiting state and claims the open pages.
  skipWaiting: true,
  clientsClaim: true,
  runtimeCaching: [
    {
      matcher: isBuildAsset,
      // `/_next/static/*` is content-hashed and immutable, so a cached copy can
      // never be wrong. `/@powersync/*` is deliberately absent from runtime
      // caching (ADR-0028): those assets are precached with a revision derived
      // from the installed SDK version, and the precache route — registered
      // ahead of everything here — answers them.
      handler: new CacheFirst({
        cacheName: 'rv-checklist-build-assets',
        plugins: [
          new CacheableResponsePlugin({ statuses: [200] }),
          new ExpirationPlugin({
            maxEntries: 256,
            maxAgeSeconds: YEAR_IN_SECONDS,
          }),
        ],
      }),
    },
    {
      matcher: isNavigation,
      // No `networkTimeoutSeconds`: a slow network must still win, or online
      // behaviour would stop being what it was. The cache answers only when
      // the network genuinely fails.
      //
      // Only a 200 is cached. A navigation request carries `redirect:
      // 'manual'`, so the middleware's redirect to `/welcome` arrives as an
      // opaque redirect (status 0) — passed straight back to the browser to
      // follow, and never stored as if it were the page.
      handler: new NetworkFirst({
        cacheName: 'rv-checklist-pages',
        plugins: [
          new CacheableResponsePlugin({ statuses: [200] }),
          new ExpirationPlugin({ maxEntries: 64 }),
        ],
      }),
    },
    {
      matcher: isRouterPayload,
      handler: new NetworkFirst({
        cacheName: 'rv-checklist-router-payloads',
        plugins: [
          new CacheableResponsePlugin({ statuses: [200] }),
          new ExpirationPlugin({ maxEntries: 128 }),
        ],
      }),
    },
    {
      matcher: isAttachmentRequest,
      // Not a built-in Serwist strategy: cache-first here means "check every
      // named `attachments-*` cache", trip caches and the LRU alike, which
      // `CacheFirst`'s single `cacheName` cannot express (issue #151).
      handler: {
        handle: ({ request }: RouteHandlerCallbackOptions) =>
          // The original `request` already carries whatever credentials mode
          // the page issued it with — cloned rather than rebuilt from the
          // bare url, so a network fallback behaves exactly like the request
          // this worker intercepted.
          respondToAttachment(self.caches, request.url, () =>
            fetch(request.clone()),
          ),
      },
    },
  ],
  fallbacks: {
    entries: [
      {
        url: OFFLINE_URL,
        // Documents only. A build asset that misses must fail as a build
        // asset; answering it with a page of HTML would be worse than the 404.
        matcher: ({ request }) => request.destination === 'document',
      },
    ],
  },
});

serwist.addEventListeners();

/**
 * Current-trip warming's client-to-SW side (ADR-0028, issue #151): a tab
 * posts a `SwMessage` (`cache-trip`, `drop-trip`, `evict-attachment`) and
 * this is the only listener for it. `event.waitUntil` keeps the worker alive
 * for the warm — otherwise the browser is free to kill it the moment the
 * `message` handler itself returns, mid-fetch.
 */
self.addEventListener('message', (event: ExtendableMessageEvent) => {
  event.waitUntil(
    handleSwMessage(self.caches, event.data, (url) =>
      fetch(url, { credentials: 'include' }),
    ),
  );
});

/**
 * The offline attachment outbox's flush (ADR-0028, issue #152): one-shot
 * Background Sync, registered by the page (`enqueueAttachmentCapture` in
 * `@rv-checklist/web-data-access`) every time a capture queues. `waitUntil`
 * with a **rejected** promise is this API's own retry signal — resolving
 * always, regardless of `shouldRetry`, would tell the browser the sync
 * succeeded and it would never come back for the entries left pending.
 */
self.addEventListener('sync', (event: Event) => {
  const syncEvent = event as SyncEvent;
  if (syncEvent.tag !== ATTACHMENT_OUTBOX_SYNC_TAG) return;
  syncEvent.waitUntil(
    (async () => {
      const db = await openOutboxDatabase();
      const { shouldRetry } = await flushOutbox({
        db,
        apiBaseUrl: __API_BASE_URL__,
        fetcher: (input, init) => fetch(input, init),
        broadcast: (message) => {
          const channel = new BroadcastChannel(OUTBOX_BROADCAST_CHANNEL);
          channel.postMessage(message);
          channel.close();
        },
      });
      if (shouldRetry) {
        throw new Error('Attachment outbox has entries left to retry');
      }
    })(),
  );
});
